export const tools = [
  { id: 'dns-lookup', category: 'DNS', endpoint: '/api/dns/lookup', path: '/dns/lookup', icon: '◎', label: 'DNS Lookup', description: 'Ringkas semua record DNS penting domain.' },
  { id: 'dns-propagation', category: 'DNS', endpoint: '/api/dns/propagation', path: '/dns/propagation', icon: '◒', label: 'DNS Propagation', description: 'Bandingkan jawaban resolver publik.' },
  { id: 'dns-record-inspector', category: 'DNS', endpoint: '/api/dns/records', path: '/dns/records', icon: '▤', label: 'DNS Record Inspector', description: 'Inspeksi A, AAAA, MX, NS, TXT, SOA, dan CAA.' },
  { id: 'dnssec-analyzer', category: 'DNS', endpoint: '/api/dns/dnssec', path: '/dns/dnssec', icon: '◇', label: 'DNSSEC Analyzer', description: 'Periksa metadata DNSKEY, DS, RRSIG, dan AD flag.' },
  { id: 'nameserver-checker', category: 'DNS', endpoint: '/api/dns/nameservers', path: '/dns/nameservers', icon: '◫', label: 'Nameserver Checker', description: 'Cek nameserver domain dan resolusi alamatnya.' },
  { id: 'cname-chain', category: 'DNS', endpoint: '/api/dns/cname-chain', path: '/dns/cname-chain', icon: '⛓', label: 'CNAME Chain', description: 'Ikuti rantai alias CNAME sampai target akhir.' },
  { id: 'ttl-analyzer', category: 'DNS', endpoint: '/api/dns/ttl', path: '/dns/ttl', icon: '◷', label: 'TTL Analyzer', description: 'Ukur rentang TTL record dari resolver DoH.' },
  { id: 'reverse-dns', category: 'DNS', endpoint: '/api/dns/reverse', path: '/dns/reverse', icon: '↩', label: 'Reverse DNS', description: 'Cari PTR hostname dari IP domain.' },
  { id: 'ip-versions', category: 'DNS', endpoint: '/api/dns/ip-versions', path: '/dns/ip-versions', icon: '6', label: 'IPv4 / IPv6', description: 'Cek dukungan IPv4, IPv6, atau dual-stack.' },
  { id: 'authoritative-dns', category: 'DNS', endpoint: '/api/dns/authoritative', path: '/dns/authoritative', icon: '♜', label: 'Authoritative DNS', description: 'Inspeksi record melalui jalur resolver hybrid.' },
  { id: 'mail-mx-lookup', category: 'Mail', endpoint: '/api/mail/mx', path: '/mail/mx', icon: '✉', label: 'MX Lookup', description: 'Temukan MX records domain.' },
  { id: 'mail-smtp-test', category: 'Mail', endpoint: '/api/mail/smtp-test', path: '/mail/smtp-test', icon: '✉', label: 'SMTP Test', description: 'Tes koneksi SMTP dasar.' },
  { id: 'mail-smtp-banner', category: 'Mail', endpoint: '/api/mail/smtp-banner', path: '/mail/smtp-banner', icon: '✉', label: 'SMTP Banner', description: 'Ambil banner SMTP pada port 25.' },
  { id: 'mail-spf-analyzer', category: 'Mail', endpoint: '/api/mail/spf', path: '/mail/spf', icon: '✉', label: 'SPF Analyzer', description: 'Analisis record SPF domain.' },
  { id: 'mail-dkim-analyzer', category: 'Mail', endpoint: '/api/mail/dkim', path: '/mail/dkim', icon: '✉', label: 'DKIM Analyzer', description: 'Periksa DKIM record (opsional isi selector, atau biarkan kosong untuk deteksi otomatis).' },
  { id: 'mail-dmarc-analyzer', category: 'Mail', endpoint: '/api/mail/dmarc', path: '/mail/dmarc', icon: '✉', label: 'DMARC Analyzer', description: 'Analisis record DMARC domain.' },
  { id: 'mail-ptr-lookup', category: 'Mail', endpoint: '/api/mail/ptr', path: '/mail/ptr', icon: '✉', label: 'PTR / Reverse DNS', description: 'Cek PTR record server email.' },
  { id: 'mail-tls-check', category: 'Mail', endpoint: '/api/mail/tls', path: '/mail/tls', icon: '✉', label: 'TLS Check', description: 'Periksa sertifikat TLS port 465.' },
  { id: 'mail-starttls', category: 'Mail', endpoint: '/api/mail/starttls', path: '/mail/starttls', icon: '✉', label: 'STARTTLS', description: 'Uji upgrade STARTTLS pada port 587.' },
  { id: 'mail-blacklist-check', category: 'Mail', endpoint: '/api/mail/blacklist', path: '/mail/blacklist', icon: '✉', label: 'Blacklist Check', description: 'Cek reputasi IP di DNSBL populer.' },
  { id: 'mail-smtp-connectivity', category: 'Mail', endpoint: '/api/mail/connectivity', path: '/mail/connectivity', icon: '✉', label: 'SMTP Connectivity', description: 'Probe port 25, 465, 587, 2525.' },
  { id: 'wordpress-version', category: 'WordPress', endpoint: '/api/wordpress/version', path: '/wordpress/version', icon: '◌', label: 'WordPress Version', description: 'Deteksi versi WordPress yang terpublikasi.' },
  { id: 'wordpress-php', category: 'WordPress', endpoint: '/api/wordpress/php', path: '/wordpress/php', icon: '◌', label: 'PHP Version', description: 'Periksa sinyal versi PHP dari header respons.' },
  { id: 'wordpress-theme', category: 'WordPress', endpoint: '/api/wordpress/theme', path: '/wordpress/theme', icon: '◌', label: 'Theme', description: 'Deteksi theme WordPress dari asset halaman.' },
  { id: 'wordpress-plugins', category: 'WordPress', endpoint: '/api/wordpress/plugins', path: '/wordpress/plugins', icon: '◌', label: 'Plugins', description: 'Deteksi plugin yang terekspos di source halaman.' },
  { id: 'wordpress-rest-api', category: 'WordPress', endpoint: '/api/wordpress/rest-api', path: '/wordpress/rest-api', icon: '◌', label: 'REST API', description: 'Periksa ketersediaan dan respons REST API.' },
  { id: 'wordpress-xmlrpc', category: 'WordPress', endpoint: '/api/wordpress/xmlrpc', path: '/wordpress/xmlrpc', icon: '◌', label: 'XML-RPC', description: 'Periksa endpoint XML-RPC secara pasif.' },
  { id: 'wordpress-wp-login', category: 'WordPress', endpoint: '/api/wordpress/wp-login', path: '/wordpress/wp-login', icon: '◌', label: 'wp-login', description: 'Periksa akses halaman login WordPress.' },
  { id: 'wordpress-wp-json', category: 'WordPress', endpoint: '/api/wordpress/wp-json', path: '/wordpress/wp-json', icon: '◌', label: 'wp-json', description: 'Ambil respons endpoint wp-json.' },
  { id: 'wordpress-security-headers', category: 'WordPress', endpoint: '/api/wordpress/security-headers', path: '/wordpress/security-headers', icon: '◌', label: 'Security Headers', description: 'Periksa header keamanan halaman WordPress.' },
  { id: 'wordpress-mixed-content', category: 'WordPress', endpoint: '/api/wordpress/mixed-content', path: '/wordpress/mixed-content', icon: '◌', label: 'Mixed Content', description: 'Deteksi asset HTTP pada halaman HTTPS.' },
  { id: 'wordpress-ssl', category: 'WordPress', endpoint: '/api/wordpress/ssl', path: '/wordpress/ssl', icon: '◌', label: 'SSL', description: 'Periksa sinyal HTTPS dan HSTS WordPress.' },
  { id: 'wordpress-performance', category: 'WordPress', endpoint: '/api/wordpress/performance', path: '/wordpress/performance', icon: '◌', label: 'Performance', description: 'Ukur waktu dan ukuran respons halaman.' },
  { id: 'wordpress-cache', category: 'WordPress', endpoint: '/api/wordpress/cache', path: '/wordpress/cache', icon: '◌', label: 'Cache', description: 'Periksa header caching dan CDN.' },
  { id: 'wordpress-db-hints', category: 'WordPress', endpoint: '/api/wordpress/db-hints', path: '/wordpress/db-hints', icon: '◌', label: 'Database hints', description: 'Cari sinyal konfigurasi internal yang terekspos.' },
  { id: 'wordpress-vuln-signals', category: 'WordPress', endpoint: '/api/wordpress/vuln-signals', path: '/wordpress/vuln-signals', icon: '◌', label: 'Vulnerability signals', description: 'Cari sinyal paparan umum tanpa eksploitasi.' },
  { id: 'web-http-status', category: 'Web', endpoint: '/api/web/http-status', path: '/web/http-status', icon: '↗', label: 'HTTP Status', description: 'Periksa status HTTPS, redirect, dan header respons penting.' },
  { id: 'web-redirect-chain', category: 'Web', endpoint: '/api/web/redirect-chain', path: '/web/redirect-chain', icon: '↗', label: 'Redirect Chain', description: 'Ikuti rangkaian redirect sampai URL akhir.' },
  { id: 'web-ssl', category: 'Web', endpoint: '/api/web/ssl', path: '/web/ssl', icon: '◆', label: 'SSL/TLS', description: 'Analisis protokol dan cipher TLS.' },
  { id: 'web-certificate', category: 'Web', endpoint: '/api/web/certificate', path: '/web/certificate', icon: '◇', label: 'Certificate', description: 'Periksa detail sertifikat X.509.' },
  { id: 'web-security-headers', category: 'Web', endpoint: '/api/web/security-headers', path: '/web/security-headers', icon: '▣', label: 'Security Headers', description: 'Periksa header keamanan HTTP.' },
  { id: 'web-http-headers', category: 'Web', endpoint: '/api/web/http-headers', path: '/web/http-headers', icon: '▤', label: 'HTTP Headers', description: 'Tampilkan seluruh header respons.' },
  { id: 'web-compression', category: 'Web', endpoint: '/api/web/compression', path: '/web/compression', icon: '◌', label: 'Compression', description: 'Deteksi kompresi gzip, deflate, atau br.' },
  { id: 'web-http2', category: 'Web', endpoint: '/api/web/http2', path: '/web/http2', icon: 'Ⅱ', label: 'HTTP/2', description: 'Cek dukungan protokol HTTP/2.' },
  { id: 'web-http3', category: 'Web', endpoint: '/api/web/http3', path: '/web/http3', icon: 'Ⅲ', label: 'HTTP/3', description: 'Cek dukungan protokol HTTP/3.' },
  { id: 'web-response-time', category: 'Web', endpoint: '/api/web/response-time', path: '/web/response-time', icon: '◷', label: 'Response Time', description: 'Ukur waktu respons HTTPS.' },
  { id: 'web-server', category: 'Web', endpoint: '/api/web/server', path: '/web/server', icon: '▦', label: 'Server', description: 'Identifikasi header server publik.' },
  { id: 'web-cdn', category: 'Web', endpoint: '/api/web/cdn', path: '/web/cdn', icon: '☁', label: 'CDN', description: 'Deteksi sinyal CDN dari header respons.' },
  { id: 'web-techstack', category: 'Web', endpoint: '/api/web/techstack', path: '/web/techstack', icon: '⌘', label: 'Tech Stack Detection', description: 'Deteksi teknologi publik dari HTML.' },
  { id: 'web-whois', category: 'Web', endpoint: '/api/web/whois', path: '/web/whois', icon: '◈', label: 'WHOIS (Web)', description: 'Lookup WHOIS domain melalui kategori Web.' },
  { id: 'ssl-certificate', category: 'SSL', endpoint: '/api/ssl/certificate', path: '/ssl/certificate', icon: '◆', label: 'SSL Certificate', description: 'Cek penerbit, masa berlaku, SAN, protokol, dan cipher TLS.' },
  { id: 'ssl-issuer', category: 'SSL', endpoint: '/api/ssl/issuer', path: '/ssl/issuer', icon: '◆', label: 'Issuer', description: 'Periksa penerbit sertifikat TLS.' },
  { id: 'ssl-expiration', category: 'SSL', endpoint: '/api/ssl/expiration', path: '/ssl/expiration', icon: '◷', label: 'Expiration', description: 'Periksa masa berlaku dan sisa hari sertifikat.' },
  { id: 'ssl-san', category: 'SSL', endpoint: '/api/ssl/san', path: '/ssl/san', icon: '◇', label: 'SAN', description: 'Daftar Subject Alternative Name sertifikat.' },
  { id: 'ssl-chain', category: 'SSL', endpoint: '/api/ssl/chain', path: '/ssl/chain', icon: '⛓', label: 'Chain', description: 'Inspeksi rantai sertifikat TLS.' },
  { id: 'ssl-tls12', category: 'SSL', endpoint: '/api/ssl/tls12', path: '/ssl/tls12', icon: 'Ⅱ', label: 'TLS 1.2', description: 'Cek dukungan handshake TLS 1.2.' },
  { id: 'ssl-tls13', category: 'SSL', endpoint: '/api/ssl/tls13', path: '/ssl/tls13', icon: 'Ⅲ', label: 'TLS 1.3', description: 'Cek dukungan handshake TLS 1.3.' },
  { id: 'ssl-cipher', category: 'SSL', endpoint: '/api/ssl/cipher', path: '/ssl/cipher', icon: '▣', label: 'Cipher', description: 'Periksa cipher suite hasil negosiasi.' },
  { id: 'ssl-ocsp', category: 'SSL', endpoint: '/api/ssl/ocsp', path: '/ssl/ocsp', icon: '◌', label: 'OCSP', description: 'Periksa metadata OCSP pasif.' },
  { id: 'ssl-hsts', category: 'SSL', endpoint: '/api/ssl/hsts', path: '/ssl/hsts', icon: '▤', label: 'HSTS', description: 'Periksa Strict-Transport-Security.' },
  { id: 'ssl-ct', category: 'SSL', endpoint: '/api/ssl/ct', path: '/ssl/ct', icon: '◈', label: 'Certificate Transparency', description: 'Periksa metadata CT yang tersedia.' },
  { id: 'domain-whois', category: 'Domain', endpoint: '/api/domain/whois', path: '/domain/whois', icon: '◈', label: 'WHOIS Domain', description: 'Cari registrar, tanggal domain, nameserver, dan status WHOIS.' },
  { id: 'network-connectivity', category: 'Network', endpoint: '/api/network/connectivity', path: '/network/connectivity', icon: '⌁', label: 'Network Connectivity', description: 'Uji resolusi DNS dan koneksi TCP ke port web umum.' }
]

export const toolById = Object.fromEntries(tools.map((tool) => [tool.id, tool]))
